### ISSUE TITLE
readme figure

### ISSUE THREAD

**Issue by bernakabadayi** [kevin-kaixu/partnet-symh#2]
![Screenshot 2021-01-13 at 14 17 30](https://user-images.githubusercontent.com/9625842/104457252-d756cc80-55ba-11eb-9ec5-4dd15cc7e5b1.png)
Hi, is there any chance to fix the figure in the readme?

Thanks, 
Berna

**Comment by kevin-kaixu** [comment]
Fixed.

**Comment by bernakabadayi** [comment]
thanks :)
