### ISSUE TITLE
MAYBE YOUR DATASET IS NOT COMPLETE?

### ISSUE THREAD

**Issue by lidan233** [kevin-kaixu/partnet-symh#3]
Can you tell me the meaning of the field named 'cell_boxs_correspond_objSerialNumber' in your 'part mesh indices' directory of your dataset? For example, if you choose the 'bed' category and the obj file named '10027.obj', you notice that there are 45 leaf nodes and 63 parts of this mesh. However, I don' know how to build the relationship between the 45 leaf and the 63 parts. You know the max index of the 'part mesh indices' is 71, which is more than 63. There, I can not find the information, which help me build the relationship between the 45 nodes and 63 parts. And I don't know the meaning of 'cell_boxs_correspond_objSerialNumber' field. Thank you!

**Comment by lidan233** [comment]
Can you help me?

**Comment by FENGGENYU** [comment]
Hi,

1. I don't find 'cell_boxs_correspond_objSerialNumber' file in part mesh indices. Where do you find it? Besides, this file is not used in shape hierarchy building code.

2. Because we only need half part of symmetry part pairs(The other part can be recovered by symmetry parameters), so the number of parts are usually more than the number of our tree leaves. Please check the example figure in the instruction page and read section B about 'part mesh indices' carefully, where the relation between structure tree leaves and mesh parts are illustrated.

Yours.

**Comment by FENGGENYU** [comment]
> Can you help me?

Hi,

I don't find 'cell_boxs_correspond_objSerialNumber' file in part mesh indices. Where do you find it? Besides, this file is not used in shape hierarchy building code.

Because we only need half part of symmetry part pairs(The other part can be recovered by symmetry parameters), so the number of original mesh parts are usually more than the number of our tree leaves. Please check the example figure in the instruction page and read section B about 'part mesh indices' carefully, where the relation between structure tree leaves and mesh parts are illustrated.

Yours.

**Comment by lidan233** [comment]
Thank you! Firstly, I notice your work doesn't need the label of each mesh part.  Secondly, you know, I want to label each face of all the obj files, but only your leaf nodes have labels. Therefore, I really want to find the relationship between your leaf nodes and mesh parts so that I can get the label of each mesh part. I notice the information can find in mat files of the directory named "part mesh indices". However, each mat file in "part mesh indices" only has a meaningful field named "cell_boxs_correspond_objSerialNumber", which usually has the same size as  all your leaf nodes. In section B, you say " you can find the sixth part mesh for node 7 in 'objs' class from result_after_merging.json file for this shape". Therefore, I think each number in the  field "cell_boxs_correspond_objSerialNumber" means the corresponded mesh part id of each leaf node. But I find some numbers are bigger than mesh part number. Please notice! I say the number of "part mesh indices" is more than the number of original mesh parts. 

At last, you can find the field "cell_boxs_correspond_objSerialNumber" in each mat file of the directory named "part mesh indices", such as "https://www.dropbox.com/sh/el63rv14d01mk89/AAANX5fxfZ5vV7ygTmj-I_ema?dl=0&file_subpath=%2FBed%2Fpart+mesh+indices&preview=Bed.zip".  At the same time, the field is the only field you can find in these mat files.

**Comment by lidan233** [comment]
For example, you can not find the 73th part in the obj file named '10027.obj' with bed category because the obj file only has 63 parts(73>63). However, the 73  is existed in '1.mat' of your directory named "part mesh indices". 

All in all, can you tell me how to get the corresponded mesh part id of each leaf node? Maybe your section B is not complete. In other words, I can not find the sixth part mesh for node 7 in 'objs' class from result_after_merging.json file for this shape because the shape only has five parts.

**Comment by FENGGENYU** [comment]
> For example, you can not find the 73th part in the obj file named '10027.obj' with bed category because the obj file only has 63 parts(73>63). However, the 73 is existed in '1.mat' of your directory named "part mesh indices".
> 
> All in all, can you tell me how to get the corresponded mesh part id of each leaf node? Maybe your section B is not complete. In other words, I can not find the sixth part mesh for node 7 in 'objs' class from result_after_merging.json file for this shape because the shape only has five parts.

Hi, I just checked 1.mat in bed category, it doesn't have problem.

1. cell_boxs_correspond_objSerialNumber means "part mesh indices" on our website, we will make it clear. This field and the shape_name field are the only fields you can find in these mat files.

2. The original Stanford PartNet dataset contains 72 objs files in its 'objs' directory for 10027. I don't know why you said only 63 part meshes. Do you use the right dataset? And the maximum part id in our part mesh indices file(1.mat) is '71', so it has no problem. Where do you find 73th part?

**Comment by lidan233** [comment]
> > For example, you can not find the 73th part in the obj file named '10027.obj' with bed category because the obj file only has 63 parts(73>63). However, the 73 is existed in '1.mat' of your directory named "part mesh indices".
> > All in all, can you tell me how to get the corresponded mesh part id of each leaf node? Maybe your section B is not complete. In other words, I can not find the sixth part mesh for node 7 in 'objs' class from result_after_merging.json file for this shape because the shape only has five parts.
> 
> Hi, I just checked 1.mat in bed category, it doesn't have problem.
> 
> 1. cell_boxs_correspond_objSerialNumber means "part mesh indices" on our website, we will make it clear. This field and the shape_name field are the only fields you can find in these mat files.
> 2. The original Stanford PartNet dataset contains 72 objs files in its 'objs' directory for 10027. I don't know why you said only 63 part meshes. Do you use the right dataset? And the maximum part id in our part mesh indices file(1.mat) is '71', so it has no problem. Where do you find 73th part?

Never mind. 73 is an example. So, your suggestion is to  use the original dataset of PartNet? Thanks.

**Comment by FENGGENYU** [comment]
> > > For example, you can not find the 73th part in the obj file named '10027.obj' with bed category because the obj file only has 63 parts(73>63). However, the 73 is existed in '1.mat' of your directory named "part mesh indices".
> > > All in all, can you tell me how to get the corresponded mesh part id of each leaf node? Maybe your section B is not complete. In other words, I can not find the sixth part mesh for node 7 in 'objs' class from result_after_merging.json file for this shape because the shape only has five parts.
> > 
> > 
> > Hi, I just checked 1.mat in bed category, it doesn't have problem.
> > 
> > 1. cell_boxs_correspond_objSerialNumber means "part mesh indices" on our website, we will make it clear. This field and the shape_name field are the only fields you can find in these mat files.
> > 2. The original Stanford PartNet dataset contains 72 objs files in its 'objs' directory for 10027. I don't know why you said only 63 part meshes. Do you use the right dataset? And the maximum part id in our part mesh indices file(1.mat) is '71', so it has no problem. Where do you find 73th part?
> 
> Never mind. 73 is an example. So, your suggestion is to use the original dataset of PartNet? Thanks.

Yes, you still need to download original PartNet dataset for part meshes. Our data and code will help you organize them into a symmetry-aware hierarchy.

You are welcome. 

Yours
